# -*- coding: utf-8 -*-
"""CodeSignal Reset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HxzRnZkN20-Y9wg68rvladJzHhfEREvq

## centuryFromYear

Given a year, return the century it is in. The first century spans from the year 1 up to and 
including the year 100, the second - from the year 101 up to and including the year 200, etc.
"""

def centuryFromYear(year):
    return year//100 + (year%100 != 0)

"""this solution utilizes floor division and boolean values as part of a mathematical expression.

## checkPalindrome

Given the string, check if it is a palindrome.

Example

<ul>
<li>For <code>inputString = "aabaa"</code>, the output should be<br>
<code>checkPalindrome(inputString) = true</code>;</li>
<li>For <code>inputString = "abac"</code>, the output should be<br>
<code>checkPalindrome(inputString) = false</code>;</li>
<li>For <code>inputString = "a"</code>, the output should be<br>
<code>checkPalindrome(inputString) = true</code>.</li>
</ul>
"""

def checkPalindrome(inputString):
    return inputString == inputString[::-1]